- name: Install mysql server
    ansible.builtin.dnf:
      name: mysql-server
      state: latest

  - name: start and enable my sqlserver
    ansible.builtin:service:
    name: mysqld
    state: started
    enable: yes

  - name: install python mysql   dependencies
    ansible.builtin.pip:
      name: 
      - PyMySQL
      - cryptography
      executable: pip3.9

  # check password already setup or not
  - name: check DB connection
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: "{{ login_host }}"
    ignore_errors: yes
    register: mysql_connection_output

    -name: print output
    ansilble.builtin.debug:
      msg: "output: {{mysql_connection_output}}"  

  - name: setup root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{mysql_root_password}}"  
    when: mysql_connection_output.failed is true
